version: '3.8'

networks:
        AzubiDevOps-Netz:

services:
        db:
                image: mysql
                cap_add:
                      - SYS_NICE
                restart: always
                environment:
                      - MYSQL_DATABASE=customerapi
                      - MYSQL_ROOT_PASSWORD=adminadmin
                ports:
                      - 3306:3306
                volumes:
                      - db:/var/lib/mysql
                      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
                container_name: mysql
                networks:
                        - AzubiDevOps-Netz
        java:
                ports:
                        - 8081:8081
                build:
                        context: /var/lib/jenkins/workspace/BuildRestService/Dockerfiles
                        dockerfile: java-dockerfile
                container_name: java
                depends_on:
                        - db
                networks:
                        - AzubiDevOps-Netz
volumes:
        db:
                driver: local


