version: '2.12'
services:
        mysql:
                image: mysql:5.7
                restart: unless-stopped
                ports:
                        - 3306:3306
                environment:
                        - MYSQL_DATABASE=customerapi
                        - MYSQL_PASSWORD=adminadmin
                        - MYSQL_ROOT_PASSWORD=adminadmin
                volumes:
                        - ./init.sql:/docker-entrypoint-initdb.d/setup.sql
                        - /data/database:/var/lib/mysql
                command: --init-file init.sql
                container_name: mysql
                networks:
                        - AzubiDevOps-Netz

networks:
        AzubiDevOps-Netz:
                ipam:
                        driver: default
                        config:
                                - subnet: "192.168.0.0/24"
