version: '3.8'

networks:
        AzubiDevOps-Netz:
                ipam:
                        driver: default
                        config:
                                - subnet: "192.168.0.0/24"

services:
        db:
                image: mysql
                cap_add:
                      - SYS_NICE
                hostname: mysql
                restart: always
                environment:
                      - MYSQL_DATABASE=customerapi
                      - MYSQL_ROOT_PASSWORD=adminadmin

                volumes:
                      - db:/var/lib/mysql
                      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
                container_name: mysql
                networks:
                        - AzubiDevOps-Netz
        java:
                ports:
                        - "8082:8080"
                build:
                        context: /var/lib/jenkins/workspace/BuildRestService/Dockerfiles
                        dockerfile: java-dockerfile
                container_name: java
                depends_on:
                        - apache
                networks:
                        - AzubiDevOps-Netz
        apache:
                image: httpd:latest
                container_name: my-apache-app
                ports:
                        - '8080:80'
                volumes:
                        - ./website:/usr/local/apache2/htdocs
                depends_on:
                        - db
                networks:
                        - AzubiDevOps-Netz
volumes:
        db:
                driver: local


