version: '3.8'
services:
        db:
                image: mysql:8.0
                cap_add:
                      - SYS_NICE
                restart: always
                environment:
                      - MYSQL_DATABASE=customerapi
                      - MYSQL_ROOT_PASSWORD=adminadmin
                ports:
                      - '3306:3306'
                volumes:
                      - db:/var/lib/mysql
                      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
                volumes:
                        db:
                                driver: local
                container_name: mysql
                networks:
                        - AzubiDevOps-Netz

networks:
        AzubiDevOps-Netz:
                ipam:
                        driver: default
                        config:
                                - subnet: "192.168.0.0/24"
